import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:supabase_flutter/supabase_flutter.dart'; 
import '../services/api_service.dart';
import '../services/auth_service.dart';

class ConsultantScreen extends StatefulWidget {
  const ConsultantScreen({super.key});

  @override
  State<ConsultantScreen> createState() => _ConsultantScreenState();
}

class _ConsultantScreenState extends State<ConsultantScreen> {
  final TextEditingController _controller = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  
  // Initial message to set context for the user
  // We will load history into this list
  final List<Map<String, String>> _messages = [];
  
  bool _loading = false;
  bool _initializing = true;

  @override
  void initState() {
    super.initState();
    _loadChatHistory();
  }

  @override
  void dispose() {
    _controller.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  // --- 1. LOAD HISTORY ---
  Future<void> _loadChatHistory() async {
    final user = AuthService.instance.currentUser;
    if (user == null) {
      setState(() => _initializing = false);
      return;
    }

    try {
      final supabase = Supabase.instance.client;
      
      // Fetch past interactions
      final response = await supabase
          .from('consultant_logs')
          .select()
          .eq('user_id', user.id)
          .order('created_at', ascending: true); // Oldest first for chat flow

      if (mounted) {
        setState(() {
          _messages.clear();
          // Add default greeting if history is empty, or just at the top always?
          // Let's add it at the top always for context.
          _messages.add({
            "role": "ai", 
            "text": "Hello! I have access to your past conversation history. Ask me anything about what you've discussed previously."
          });

          for (var log in response) {
            // Each row has 'question' (User) and 'answer' (AI)
            if (log['question'] != null) {
              _messages.add({"role": "user", "text": log['question']});
            }
            if (log['answer'] != null) {
              _messages.add({"role": "ai", "text": log['answer']});
            }
          }
          _initializing = false;
        });
        
        // Scroll to bottom after loading
        WidgetsBinding.instance.addPostFrameCallback((_) => _scrollToBottom());
      }
    } catch (e) {
      print("Error loading history: $e");
      if (mounted) setState(() => _initializing = false);
    }
  }

  // --- 2. SAVE INTERACTION ---
  Future<void> _saveInteraction(String question, String answer) async {
    final user = AuthService.instance.currentUser;
    if (user == null) return;

    try {
      final supabase = Supabase.instance.client;
      await supabase.from('consultant_logs').insert({
        'user_id': user.id,
        'question': question,
        'answer': answer,
        // 'created_at' is auto-generated by Supabase
      });
    } catch (e) {
      print("Error saving interaction: $e");
    }
  }

  // --- 3. SEND MESSAGE ---
  void _sendMessage() async {
    final text = _controller.text.trim();
    if (text.isEmpty) return;

    final user = AuthService.instance.currentUser;
    if (user == null) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("User not logged in. Please log in to use this feature."),
            backgroundColor: Colors.redAccent,
          )
        );
      }
      return;
    }

    // Optimistic UI Update
    setState(() {
      _messages.add({"role": "user", "text": text});
      _loading = true;
      _controller.clear();
    });
    
    _scrollToBottom();

    try {
      // Call the Backend API (RAG + Graph Update logic happens on server)
      final api = Provider.of<ApiService>(context, listen: false);
      final answer = await api.askConsultant(user.id, text);

      if (mounted) {
        setState(() {
          _messages.add({"role": "ai", "text": answer});
        });
        _scrollToBottom();
        
        // Persist this turn to Supabase
        await _saveInteraction(text, answer);
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _messages.add({"role": "ai", "text": "Error connecting to consultant: $e"});
        });
        _scrollToBottom();
      }
    } finally {
      if (mounted) {
        setState(() {
          _loading = false;
        });
      }
    }
  }

  void _scrollToBottom() {
    Future.delayed(const Duration(milliseconds: 100), () {
      if (_scrollController.hasClients) {
        _scrollController.animateTo(
          _scrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          "Consultant AI",
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
      ),
      body: _initializing 
        ? const Center(child: CircularProgressIndicator())
        : Column(
            children: [
              // --- CHAT HISTORY AREA ---
              Expanded(
                child: ListView.builder(
                  controller: _scrollController,
                  padding: const EdgeInsets.all(16),
                  itemCount: _messages.length,
                  itemBuilder: (context, index) {
                    final msg = _messages[index];
                    bool isUser = msg['role'] == "user";
                    
                    return Align(
                      alignment: isUser ? Alignment.centerRight : Alignment.centerLeft,
                      child: Container(
                        margin: const EdgeInsets.symmetric(vertical: 8),
                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                        constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width * 0.75),
                        decoration: BoxDecoration(
                          color: isUser ? theme.colorScheme.primary : theme.colorScheme.surfaceContainer,
                          borderRadius: BorderRadius.only(
                            topLeft: const Radius.circular(16),
                            topRight: const Radius.circular(16),
                            bottomLeft: isUser ? const Radius.circular(16) : Radius.zero,
                            bottomRight: isUser ? Radius.zero : const Radius.circular(16),
                          ),
                          boxShadow: [
                            BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 4, offset: const Offset(0, 2))
                          ]
                        ),
                        child: isUser 
                          ? Text(
                              msg['text']!, 
                              style: const TextStyle(color: Colors.white, fontSize: 15)
                            )
                          : MarkdownBody(
                              data: msg['text']!, 
                              styleSheet: MarkdownStyleSheet(
                                p: TextStyle(color: theme.colorScheme.onSurface, fontSize: 15),
                              )
                            ),
                      ),
                    );
                  },
                ),
              ),
              
              // --- LOADING INDICATOR ---
              if (_loading) 
                Padding(
                  padding: const EdgeInsets.symmetric(vertical: 8.0),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      SizedBox(
                        width: 16, 
                        height: 16, 
                        child: CircularProgressIndicator(strokeWidth: 2, color: theme.colorScheme.primary)
                      ),
                      const SizedBox(width: 8),
                      Text("Consultant is thinking...", style: TextStyle(color: theme.colorScheme.onSurfaceVariant, fontSize: 12)),
                    ],
                  ),
                ),

              // --- INPUT AREA ---
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: theme.colorScheme.surface,
                  boxShadow: [
                    BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 10, offset: const Offset(0, -2))
                  ]
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: TextField(
                        controller: _controller,
                        decoration: InputDecoration(
                          hintText: "Ask about past sessions...",
                          hintStyle: TextStyle(color: theme.colorScheme.onSurfaceVariant),
                          filled: true,
                          fillColor: theme.colorScheme.surfaceContainerHighest,
                          contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                          border: OutlineInputBorder(
                            borderRadius: BorderRadius.circular(30), 
                            borderSide: BorderSide.none
                          ),
                        ),
                        onSubmitted: (_) => _sendMessage(),
                      ),
                    ),
                    const SizedBox(width: 10),
                    GestureDetector(
                      onTap: _loading ? null : _sendMessage,
                      child: CircleAvatar(
                        radius: 24,
                        backgroundColor: _loading ? theme.colorScheme.surfaceContainerHighest : theme.colorScheme.primary,
                        child: Icon(Icons.send_rounded, color: _loading ? theme.colorScheme.onSurfaceVariant : Colors.white, size: 20),
                      ),
                    )
                  ],
                  
                ),
              )
            ],
          ),
    );
  }
}